#!/bin/bash

# Ubuntu Hardening & Security Script
# Run with: sudo bash ubuntu_harden.sh

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Log file
LOG_FILE="/var/log/ubuntu_harden.log"

# Function for logging
log_message() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
}

# Function for colored output
print_status() {
    case $1 in
        "success") echo -e "${GREEN}[✓]${NC} $2" ;;
        "error") echo -e "${RED}[✗]${NC} $2" ;;
        "warning") echo -e "${YELLOW}[!]${NC} $2" ;;
        "info") echo -e "[i] $2" ;;
    esac
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    print_status "error" "This script must be run as root (use sudo)"
    exit 1
fi

# Get server IP
SERVER_IP=$(hostname -I | awk '{print $1}')
[ -z "$SERVER_IP" ] && SERVER_IP="your_server_ip"

# Get current user
CURRENT_USER=${SUDO_USER:-$USER}
if [ "$CURRENT_USER" = "root" ]; then
    CURRENT_USER=$(who am i | awk '{print $1}')
fi
[ -z "$CURRENT_USER" ] && CURRENT_USER="ubuntu"

log_message "Starting Ubuntu hardening script for user: $CURRENT_USER"

# ====================
# 1. SYSTEM UPDATES
# ====================
print_status "info" "Starting system updates..."

apt update
if [ $? -eq 0 ]; then
    print_status "success" "Package list updated"
else
    print_status "error" "Failed to update package list"
    exit 1
fi

apt upgrade -y
if [ $? -eq 0 ]; then
    print_status "success" "Packages upgraded"
else
    print_status "error" "Failed to upgrade packages"
fi

apt autoremove -y
apt autoclean

# ====================
# 2. SSH HARDENING
# ====================
print_status "info" "Hardening SSH configuration..."

# Backup original SSH config
if [ -f "/etc/ssh/sshd_config" ]; then
    BACKUP_FILE="/etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)"
    cp /etc/ssh/sshd_config "$BACKUP_FILE"
    print_status "success" "SSH config backed up to $BACKUP_FILE"
fi

# Create secure SSH config
cat > /etc/ssh/sshd_config << EOF
# SSH Server Configuration - Generated by hardening script $(date)
# Backup: $BACKUP_FILE

# Port configuration
Port 22
Port 2222

# Protocol
Protocol 2

# Logging
LogLevel INFO
PrintMotd no
PrintLastLog yes
SyslogFacility AUTH

# Authentication
PermitRootLogin no
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 60
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication no
PubkeyAuthentication yes
GSSAPIAuthentication no
UsePAM yes
UseDNS no

# Security
X11Forwarding no
AllowAgentForwarding no
AllowTcpForwarding no
PermitTunnel no
ClientAliveInterval 300
ClientAliveCountMax 2
IgnoreRhosts yes
HostbasedAuthentication no
PermitUserEnvironment no
Compression no
TCPKeepAlive yes

# Allow users
AllowUsers $CURRENT_USER

# Listen address
ListenAddress 0.0.0.0
ListenAddress ::

# Cryptography (modern settings)
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256

# Authentication methods
AuthenticationMethods publickey

# Subsystem
Subsystem sftp internal-sftp
EOF

# Set proper permissions
chmod 600 /etc/ssh/sshd_config
chown root:root /etc/ssh/sshd_config

# Set permissions on SSH host keys
find /etc/ssh -name "*_key" -exec chmod 600 {} \;
find /etc/ssh -name "*_key.pub" -exec chmod 644 {} \;

# Restart SSH
systemctl restart ssh

# Test SSH config
if sshd -t; then
    print_status "success" "SSH configuration is valid"
else
    print_status "error" "SSH configuration has errors"
    exit 1
fi

print_status "success" "SSH configuration hardened"

# ====================
# 3. FIREWALL SETUP
# ====================
print_status "info" "Configuring firewall..."

# Install UFW if not present
if ! command -v ufw &> /dev/null; then
    apt install ufw -y
fi

# Reset UFW
ufw --force reset

# Set default policies
ufw default deny incoming
ufw default allow outgoing

# Allow SSH on both ports
ufw allow 22/tcp comment 'SSH Default Port'
ufw allow 2222/tcp comment 'SSH Custom Port'

# Enable UFW
ufw --force enable
systemctl enable ufw

print_status "success" "Firewall configured"

# ====================
# 4. USER SECURITY
# ====================
print_status "info" "Configuring user security..."

# Install password quality
apt install libpam-pwquality -y

# Configure password policy
cat > /etc/security/pwquality.conf << 'EOF'
minlen = 12
minclass = 3
maxrepeat = 2
maxsequence = 3
maxclassrepeat = 2
EOF

# Configure login attempts
cat > /etc/security/faillock.conf << 'EOF'
deny = 5
unlock_time = 900
fail_interval = 900
EOF

# Configure sudo timeout
echo "Defaults timestamp_timeout=5" > /etc/sudoers.d/timeout
chmod 440 /etc/sudoers.d/timeout

# ====================
# 5. KERNEL HARDENING
# ====================
print_status "info" "Applying kernel hardening..."

cat > /etc/sysctl.d/99-security.conf << 'EOF'
# Security settings
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.ip_forward = 0
net.ipv6.conf.all.forwarding = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2
net.ipv4.conf.all.log_martians = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
fs.suid_dumpable = 0
kernel.randomize_va_space = 2
kernel.yama.ptrace_scope = 1
EOF

sysctl -p /etc/sysctl.d/99-security.conf

# ====================
# 6. FILE PERMISSIONS
# ====================
print_status "info" "Setting secure file permissions..."

chmod 600 /etc/shadow /etc/gshadow
chmod 644 /etc/passwd /etc/group

# Secure log files
find /var/log -type f -exec chmod 640 {} \;

# ====================
# 7. SECURITY TOOLS
# ====================
print_status "info" "Installing security tools..."

# Install fail2ban
apt install fail2ban -y

cat > /etc/fail2ban/jail.local << EOF
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 5
ignoreip = 127.0.0.1

[sshd]
enabled = true
port = 22,2222
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
EOF

systemctl restart fail2ban

# Install auditd
apt install auditd -y

# Install automatic updates
apt install unattended-upgrades -y

cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'EOF'
Unattended-Upgrade::Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
};
Unattended-Upgrade::Automatic-Reboot "false";
EOF

cat > /etc/apt/apt.conf.d/20auto-upgrades << 'EOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::Unattended-Upgrade "1";
APT::Periodic::AutocleanInterval "7";
EOF

# ====================
# 8. DISABLE SERVICES
# ====================
print_status "info" "Disabling unnecessary services..."

services="bluetooth cups avahi-daemon"
for service in $services; do
    if systemctl is-enabled "$service" 2>/dev/null; then
        systemctl stop "$service"
        systemctl disable "$service"
    fi
done

# ====================
# 9. FINAL SETUP
# ====================
print_status "info" "Finalizing setup..."

# Create recovery script
cat > /usr/local/bin/recover-ssh.sh << 'EOF'
#!/bin/bash
echo "=== SSH Recovery ==="
BACKUP=$(ls -t /etc/ssh/sshd_config.backup.* 2>/dev/null | head -1)
if [ -f "$BACKUP" ]; then
    cp "$BACKUP" /etc/ssh/sshd_config
    echo "Restored from: $BACKUP"
fi
ufw allow 22/tcp 2>/dev/null
systemctl restart ssh
echo "SSH restored on port 22"
EOF

chmod +x /usr/local/bin/recover-ssh.sh

# ====================
# 10. VERIFICATION
# ====================
print_status "info" "Verifying setup..."

# Check SSH ports
if netstat -tln | grep -q ":22 "; then
    print_status "success" "SSH listening on port 22"
fi
if netstat -tln | grep -q ":2222 "; then
    print_status "success" "SSH listening on port 2222"
fi

# Check UFW
if ufw status | grep -q "Status: active"; then
    print_status "success" "Firewall is active"
fi

# ====================
# 11. COMPLETE SUMMARY
# ====================
clear
echo ""
echo "==============================================="
echo "UBUNTU HARDENING COMPLETE"
echo "==============================================="
echo ""
echo "Server IP: $SERVER_IP"
echo "Username: $CURRENT_USER"
echo "SSH Ports: 22 (current), 2222 (new)"
echo ""
echo "==============================================="
echo "IMMEDIATE ACTIONS REQUIRED:"
echo "==============================================="
echo ""
echo "1. GENERATE SSH KEY (on your local machine):"
echo "   ssh-keygen -t ed25519 -C \"your_email@example.com\""
echo ""
echo "2. COPY SSH KEY TO SERVER:"
echo "   ssh-copy-id -p 2222 $CURRENT_USER@$SERVER_IP"
echo "   OR if using custom key:"
echo "   ssh-copy-id -i ~/.ssh/your_key.pub -p 2222 $CURRENT_USER@$SERVER_IP"
echo ""
echo "3. TEST NEW SSH PORT:"
echo "   ssh -p 2222 $CURRENT_USER@$SERVER_IP"
echo ""
echo "4. AFTER SUCCESSFUL TEST:"
echo "   a) Remove port 22 from SSH config:"
echo "      sudo sed -i '/^Port 22$/d' /etc/ssh/sshd_config"
echo "   b) Remove port 22 from firewall:"
echo "      sudo ufw delete allow 22/tcp"
echo "   c) Restart SSH:"
echo "      sudo systemctl restart ssh"
echo ""
echo "==============================================="
echo "AWS SPECIFIC:"
echo "==============================================="
echo "1. Update AWS Security Group to allow port 2222"
echo "2. EC2 Console → Security Groups → Inbound Rules"
echo "3. Add: Type=SSH, Port=2222, Source=Your IP"
echo ""
echo "==============================================="
echo "RECOVERY:"
echo "==============================================="
echo "If locked out, run: sudo /usr/local/bin/recover-ssh.sh"
echo "Or use AWS Console access"
echo ""
echo "==============================================="
echo "NEXT SECURITY STEPS:"
echo "==============================================="
echo "1. Setup 2FA for SSH (optional)"
echo "2. Configure log monitoring"
echo "3. Regular security audits"
echo "==============================================="

log_message "Hardening script completed successfully"
